Accedian/grafana-docker

- CHANGELOG.md
- dashboards/SSH Logins.json
- provisioning/datasources/prometheus-datasource.yaml
New Dashboard and Alert to monitor SSH Logins. If a SSH Login is successful and didn't come from Vault an Alert will be triggered
> feat(ssh login) - dashboard to monitor SSH access

- dashboards/SSH Logins.json
- dashboards/Server Certificate.json
> added cert dashboard and updated ssh logins

- dashboards/CybersecuritySparkApp.json
Asana task: https://app.asana.com/0/1166899212305697/1199342103454905/f
Link to dashboard: https://dev.dev.cyber.npav.accedian.net/grafana/d/g1nGBjTGz/cybersecuritysparkapp
> Added CybersecuritySparkApp dashboard

- CHANGELOG.md
- Dockerfile
- Makefile
- dashboards/SparkBatchJobMonitoring.json
- dashboards/SparkKafkaIngestionAndLag.json
*Feat:Added Batch Job Monitoring dashboard
*Feat:Added a new panel to Spark Ingestion and Lag dashboard 
*Fix: Added DOCKER_DEFAULT_PLATFORM for cross compilation
> Changes to grafana dashboards for 22.04 release

- dashboards/kafka-overview-consumers.json
Update Kafka Overview Consumer Dashboard
- Update All to customer wildcard regex to avoid query limit
- increase query interval for per second metric to twice scrape interval for proper data representation
https://app.asana.com/0/1200469496011803/1201392751295167/f
> update custom all and metric interval

- CHANGELOG.md
- dashboards/Custom Reports.json
https://app.asana.com/0/1201825567223644/1202005753652075/f
> Feat - Add Custom Reports dashboard

- dashboards/HDFS.json
More panels to troubleshoot possible HDFS issues.
> Local HDFS grafana board add more panels

- CHANGELOG.md
- dashboards/Roadrunner.json
Add metrics for the PersistenceService to the Roadrunner dashboard.
[Asana](https://app.asana.com/0/1199574676083399/1203406613035602/f)
> Feat - Add PersistenceService metrics to the Roadrunner dashboard

- CHANGELOG.md
- dashboards/Analytics-Streamer gNMI.json
This reverts commit 8753fcb3a29c41b1cc81a3f6ac8ceb36600c364d.
> Revert "Fix: gNMI dashboard unavailable" -> Rollback

- CHANGELOG.md
- dashboards/alert_service_dashboard.json
https://app.asana.com/0/1202421299651189/1203447968630095/f
> Add new panel with metrics

- CHANGELOG.md
- Fedex.json
- dashboards/Fedex.json
https://app.asana.com/0/1203411329194882/1203411329194909/f
> add fedex dashboard

- CHANGELOG.md
- dashboards/alert_service_dashboard.json
https://app.asana.com/0/1202421299651189/1203882620723234/f
> Fix api call duration query expression

- CHANGELOG.md
- dashboards/alert_service_dashboard.json
https://app.asana.com/0/1202421299651189/1203936039863649/f
> Refactor alert service dashboard

- dashboards/clickhouse-dashboard-cluster-analysis.json
- dashboards/clickhouse-dashboard-data-analysis.json
- dashboards/clickhouse-dashboard-query-analysis.json
- provisioning/datasources/clickhouse-datasource.yaml
I was no able to use `yaml` anchor in p`rovisioning/datasources/clickhouse-datasource.yaml` it look like this is not supported.
> Clickhouse dashboard multisources

- CHANGELOG.md
- dashboards/MOSummaryConsolidator.json
- New Dashboard for MOSummaryConsolidatorJob where deltas are captured for each tenant/objectType/msgType
- Resolves: https://app.asana.com/0/1133479128121896/1203328848884985/f
> Feat: MOSummaryConsolidator dashboard

- CHANGELOG.md
- dashboards/alert_service_dashboard.json
https://app.asana.com/0/1202421299651189/1203965761436765/f
> Alert service dashboard - Include micro-tca + minor changes

- CHANGELOG.md
- dashboards/Analytics-Streamer gNMI.json
https://app.asana.com/0/1202876257534184/1204119453925966
> Fix: Update gNMI dashboard to support multiple analytics-streamers

- CHANGELOG.md
- dashboards/foxtrot_service_dashboard.json
https://app.asana.com/0/1203669339406776/1202458568143107/f
> bootstrap Foxtrot dashboard

- CHANGELOG.md
- dashboards/foxtrot_service_dashboard.json
https://app.asana.com/0/1203669339406776/1202458568143107/f
> Foxtrot Postgres call time panel

- CHANGELOG.md
- dashboards/SparkKafkaIngestionAndLag.json
https://app.asana.com/0/1201489317584292/1204415956101184/f
> Change default time range for Spark Ingestion and Lag dashboard

- CHANGELOG.md
- dashboards/foxtrot_service_dashboard.json
https://app.asana.com/0/1203669339406776/1202458568143107/f
https://github.com/Accedian/Foxtrot/pull/37
> Foxtrot dashboards for handlers

- CHANGELOG.md
- dashboards/updateserver-dashboard.json
https://app.asana.com/0/1204139580644856/1204105776993399/f
> Roadrunner update server

- CHANGELOG.md
- dashboards/updateserver-dashboard.json
Roadrunner update server, dashboard tuning [Asana](https://app.asana.com/0/1204139580644856/1204105776993399/f)
> Roadrunner update server, dashboard tuning

- dashboards/Fedex.json
https://app.asana.com/0/1199733373661982/1204795779994090/f
> fix loading fedex dashboard

- CHANGELOG.md
- dashboards/foxtrot_service_dashboard.json
https://app.asana.com/0/1203669339406776/1202458568143107/f
> Add REST API Call duration panel to Foxtrot dashboard

- dashboards/RabbitMQ-Overview.json
[Grafana - Add RabbitMQ 3.8.0 board to grafana repo](https://app.asana.com/0/1204833075360053/1204844900122112)
> feat(rabbitmq): Add 3.8.0 Grafana dashboard

- CHANGELOG.md
- dashboards/updateserver-dashboard.json
https://app.asana.com/0/1204139580644856/1204768697549326/f
> Metrics for rollback'ed updates 

- dashboards/Weld-watcher.json
Follow up to https://github.com/Accedian/accedian-anvil/pull/6662
[Weld-watcher - Add Grafana Dashboard](https://app.asana.com/0/1203985123093075/1204969553318228)
> feat(weld-watcher): Weld watcher dashboard

- dashboards/alert_service_dashboard.json
> Alert Service dashboard ver-9

- CHANGELOG.md
- dashboards/updateserver-dashboard.json
Updateserver: Prometheus metric about RR update reverted to a deployed version [Asana](https://app.asana.com/0/1204139580644856/1204768697549331/f)
> Updateserver: Prometheus metric about RR update reverted to a deployed version

- dashboards/Fedex.json
https://app.asana.com/0/1203411329194882/1204862019995306/f
> update adh-fedex dashboard

- dashboards/CybersecuritySparkApp.json
https://app.asana.com/0/1200625808662018/1205389191588649/f
> update cybersecurity dashboard

- dashboards/Fedex.json
https://app.asana.com/0/1204956768128485/1205375393317530/f
> update fedex dashboard - add nack metrics

- CHANGELOG.md
- dashboards/GatherMetrics.json
Asana link - https://app.asana.com/0/1203450045248205/1205384205616160/f
> Added Panel for tracking gather ingestion  dict/profile violations

- CHANGELOG.md
- dashboards/roadrunner-data-flow.json
https://app.asana.com/0/1205807473497888/1205891361597234/f
> Roadrunner data flow

- CHANGELOG.md
- dashboards/Ingestion.json
https://app.asana.com/0/1205804467494021/1205817814251795
> Feat - pacemaker addition to ingestion dashboard

- CHANGELOG.md
- dashboards/GatherMetrics.json
Asana  -https://app.asana.com/0/1203450045248205/1206694555908557/f
> Fix - ingestion validations dashboard for Gather

- CHANGELOG.md
- dashboards/Telemetry Collector.json
Adds a new dashboard for reporting KPI associated with the Telemetry Collector.
[Asana](https://app.asana.com/0/1206812330405242/1207416630261414/f)
> Add dashboard for Telemetry Collector

- CHANGELOG.md
- dashboards/Roadrunner.json
https://app.asana.com/0/1207589771375551/1207591718072293/f
> Extend RR dashboard

- dashboards/SparkKafkaIngestionAndLag.json
Add Number of Monitored Objects panel to spark ingestion and lag dashboard [Asana](https://app.asana.com/0/1207589686024250/1207768839321331/f)
> Add number of MO panel to spark ingestion and lag dashboard

- CHANGELOG.md
- dashboards/SparkKafkaIngestionAndLag.json
Optimize Number of MOs panel in spark Ingestion and Lag dashborad [Asana](https://app.asana.com/0/1207589686024250/1208266838371249/f)
> Fix - Optimize Number of MOs panel in spark Ingestion and Lag dashborad

- CHANGELOG.md
- dashboards/SparkKafkaIngestionAndLag.json
Feat - Add Number of Monitored Objects panel to spark ingestion and lag dashboard [Asana](https://app.asana.com/0/1207589686024250/1207768839321331/f)
> Add Number of Monitored Objects panel to spark ingestion and lag dashboard

- CHANGELOG.md
- dashboards/capture_sensors.json
update following changes in collectd/vmagent on the capture : 
* Increase vmagent scraping time [Mohamed ISSOLAH]
* junkie collectd - only scap interfaces counters [Gabriel Ganne]
* junkie collectd - remove obsolete workers counters scrapping [Gabriel Ganne]
> update capture sensor dashboard

- CHANGELOG.md
- dashboards/Roadrunner.json
https://app.asana.com/0/1208396396222905/1208420691524941/f
> Fix metrics

- CHANGELOG.md
- dashboards/Remote-Tech-Support.json
- dashboards/SparkKafkaIngestionAndLag.json
- dashboards/Telemetry Collector.json
* Fix - missing charts from spark Ingestion and Lag [Asana](https://app.asana.com/0/1207589910511516/1208521223214145/f)
* Fix - Telemetry Collector charts data source labeling [Asana](https://app.asana.com/0/1207589910511516/1208524073684153/f)
* Fix - Tech Support Report Tool charts in Grafana report datasource not found [Asana](https://app.asana.com/0/1207589910511516/1208524073684147/f)
> Fix data source assignment issue

- CHANGELOG.md
- dashboards/Roadrunner.json
New graphs for MQTT / SNMP Trap messages and MQTT / SNMP service start / stop counters
https://app.asana.com/0/1208319030362516/1208546743487066/f
> Adding new graphs for MQTT and SNMP Trap messages count

- CHANGELOG.md
- dashboards/SparkKafkaIngestionAndLag.json
Fix - Update record count panel with updated metric labels due to spark upgrade [Asana](https://app.asana.com/0/1207966128668826/1208739770836196/f)
> Update spark ingestion and lag dashboard

- CHANGELOG.md
- dashboards/Routing Analytics Collector.json
https://app.asana.com/0/1207589770978424/1208222207550153/f
> Add dashboard for ra collector

- CHANGELOG.md
- dashboards/Roadrunner.json
https://app.asana.com/0/1208319030362516/1208447007098038/f
New metric for RoadRunner csv files validation
> feat: Adding new metrics and logging for csv files validation

- CHANGELOG.md
- dashboards/sky-topo-node-processor.json
https://app.asana.com/0/1208406814937360/1208044348370600/f
> Sky Topo Node Processor dashboard

- dashboards/Weld-Watcher_.Concurrent.Users.on.Dashboard.Monitoring.json
[Grafana Dashboard - Concurrent User Monitoring PoC](https://app.asana.com/0/1207589689131538/1209291919778494/f)
> feat(weld-watcher): Concurrent users on dashboard prometheus stats

- CHANGELOG.md
- dashboards/GatherMetrics.json
* Feat - Update gather dashboard to include Dgraph [Asana](https://app.asana.com/0/1209448326140601/1209354053207590)
> Updated gather dashboard to have dgraph

- CHANGELOG.md
- dashboards/alert-policies.json
Dashboard for Prometheus Alert Policies metrics exposed here: https://github.com/Accedian/adh-gather/pull/2145
[Asana link](https://app.asana.com/1/5557457880942/project/1209680023328208/task/1209680031105494)
Docker image: `gcr.io/npav-172917/grafana:ricamelo-dev`
> feat: alert policies dashboard

- CHANGELOG.md
- dashboards/SparkKafkaIngestionAndLag.json
* Feat: Update spark ingestion and lag dashboard with fm-alert metrics [Asana Task](https://app.asana.com/1/5557457880942/project/1210039614117048/task/1210823760990026?focus=true)
> Update spark ingestion and lag with fm-alert metrics

- CHANGELOG.md
- dashboards/CouchDB metrics-1519688661301.json
Board for couchdb open files metrics
> couchdb files board

- CHANGELOG.md
- dashboards/Object-Type-Metrics.json
- dashboards/Spark Resources.json
- dashboards/SparkKafkaIngestionAndLag.json
* Feat - Add spark_executor_runTime metric to spark resources dashboard [Asana](https://app.asana.com/1/5557457880942/project/1211248085470096/task/1211362440163023?focus=true)
* Fix - Fix Micro Batch Duration Panel [Asana](https://app.asana.com/1/5557457880942/project/1207093596205090/task/1211293213793482?focus=true)
* Fix - Remove spark-latent.* from Latent Lag board [Asana](https://app.asana.com/1/5557457880942/project/1207093596205090/task/1211211264951639?focus=true)
* Feat - Add Disk Spill, Executor Heap and Storage Heap Metric Panels to the Spark Resource Board [Asana](https://app.asana.com/1/5557457880942/pr
oject/1207093596205090/task/1211140224141531?focus=true)
> Fix spark dashboards
